from pathlib import Path
from html import escape
ROOT=Path(__file__).parent

def page(name,title,description,body):
    if name == 'case-studies/assistant-s.html':
        body = body.replace('assets/companion.svg', 'assets/assistant-s-preview.png').replace('Original conceptual illustration of a desktop companion, not a screenshot of the private application.', 'Screenshot of the animated room in Assistant S.')
    if name == 'case-studies/scribevo.html':
        body = body.replace('<h2>', '<figure><img class="diagram" src="../assets/scribevo-preview.png" alt="Prepared Scribevo product example with a reviewable correction"><figcaption>Prepared product example showing how a suggestion is reviewed.</figcaption></figure><h2>', 1)
    prefix='../' if '/' in name else ''
    url='https://slooma951.github.io/portfolio/'+name
    content=f'''<!doctype html><html lang="en-GB"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta http-equiv="Content-Security-Policy" content="default-src 'self'; img-src 'self'; style-src 'self'; script-src 'self'; object-src 'none'; base-uri 'self'; form-action 'none'"><title>{escape(title)} | Salem Elatrash</title><meta name="description" content="{escape(description)}"><link rel="canonical" href="{url}"><meta property="og:title" content="{escape(title)}"><meta property="og:description" content="{escape(description)}"><meta property="og:image" content="https://slooma951.github.io/portfolio/assets/social.png"><meta property="og:url" content="{url}"><link rel="icon" href="{prefix}favicon.svg"><link rel="stylesheet" href="{prefix}css/home.css"><script src="{prefix}js/theme.js"></script></head><body><main class="reading"><a class="back" href="{prefix}index.html#work">← Back to portfolio</a><p class="eyebrow">Salem Elatrash / {escape(title)}</p><h1>{escape(title)}</h1>{body}</main><footer class="wrap footer"><span>© 2026 Salem Elatrash</span><div><a href="{prefix}privacy.html">Privacy</a><a href="{prefix}terms.html">Terms</a></div></footer></body></html>'''
    (ROOT/name).write_text(content,encoding='utf-8')

def diagram(filename,title,steps):
    elements=[]
    for i,(label,detail) in enumerate(steps):
        y=85+i*100
        elements.append(f'<rect x="35" y="{y}" width="650" height="78" rx="12" fill="white" stroke="#d4dfed"/><circle cx="72" cy="{y+39}" r="20" fill="#e8f0fc"/><text x="72" y="{y+45}" text-anchor="middle" font-size="15" fill="#1768d8">{i+1}</text><text x="112" y="{y+29}" font-size="19" font-weight="bold">{escape(label)}</text><text x="112" y="{y+55}" font-size="14" fill="#596579">{escape(detail)}</text>')
        if i<len(steps)-1:elements.append(f'<path d="M360 {y+81}v16m-5-5 5 5 5-5" stroke="#86a1c7" fill="none" stroke-width="2"/>')
    height=105+len(steps)*100
    svg=f'<svg xmlns="http://www.w3.org/2000/svg" width="720" height="{height}" viewBox="0 0 720 {height}" role="img"><title>{escape(title)}</title><rect width="720" height="{height}" rx="18" fill="#f2f4f7"/><g font-family="Arial,sans-serif" fill="#18202f"><text x="35" y="49" font-size="23" font-weight="bold">{escape(title)}</text>'+''.join(elements)+'</g></svg>'
    (ROOT/'assets'/filename).write_text(svg,encoding='utf-8')

diagram('scribevo-flow.svg','Scribevo: the writer stays in control',[
 ('Write a sentence','Use a supported browser text field.'),
 ('Ask for writing support','The selected sentence is checked, rather than the whole document.'),
 ('Review the suggestion','See the proposed correction in context.'),
 ('Accept or dismiss','The writer decides whether the sentence changes.')])
diagram('assistant-flow.svg','Assistant S: a desktop workspace',[
 ('Choose a task','Chat, study and everyday task interfaces in one desktop app.'),
 ('Work with the assistant','A familiar interface and animated desktop companion.'),
 ('Review the result','Keep the person involved in consequential actions.')])
diagram('dvs-flow.svg','DVS Note: organise and reflect',[
 ('Capture','Write a note, add a task or record a journal entry.'),
 ('Organise','Use separate views for tasks, journals and the dashboard.'),
 ('Reflect','Review mood information alongside personal entries.')])

page('case-studies/scribevo.html','Scribevo','Writing support for dyslexic students, from a TU Dublin research project to a published Chrome extension.', '''
<p class="intro">Writing help that understands how you spell. A Chrome extension built by Salem Elatrash, beginning with the WordFlow final-year research project at TU Dublin.</p>
<div class="actions"><a class="button primary" href="https://chromewebstore.google.com/detail/pfpakhloamdgoiokaljdfhpgkbanccci">View the published extension ↗</a><a class="button" href="https://github.com/Slooma951/Scribevo">Public project overview</a></div>
<section id="project-evidence" class="project-evidence">
<p class="eyebrow">Inspect the engineering</p><h2>Project evidence</h2>
<p>Python evaluation and NumPy analysis, with selected source code, a runnable example and tests.</p>
<div class="evidence-grid">
<a href="https://github.com/Slooma951/Scribevo/tree/main/examples" target="_blank" rel="noopener noreferrer"><span class="evidence-label">Output</span><strong>Run the example ↗</strong><span>Inspect the selected code and compare its result with the saved JSON output.</span></a>
<a href="https://github.com/Slooma951/Scribevo/tree/main/evidence#methodology" target="_blank" rel="noopener noreferrer"><span class="evidence-label">Methodology</span><strong>Read the decisions ↗</strong><span>Source provenance, adaptations and the reasoning behind the example.</span></a>
<a href="https://github.com/Slooma951/Scribevo/tree/main/evidence#testing-results" target="_blank" rel="noopener noreferrer"><span class="evidence-label">Testing results</span><strong>11 example tests pass ↗</strong><span>Checked 4 October 2026. Test cases, rerun commands and verification record.</span></a>
</div><p>The selected Python code measures correct, missed and unnecessary edits. A new NumPy companion aggregates synthetic outcome labels. It is separate from the shipped extension and original research model.</p><p class="evidence-limit">These tests check the public evaluation code, not model accuracy. Product release checks and academic research remain separate evidence below.</p></section>
<h2>The problem</h2><p>A writer may know what they want to say without knowing the dictionary spelling. Sound-based spellings, missing letters and swapped letters can make ordinary spell-check suggestions unhelpful. For students, that adds another task between an idea and a written assignment.</p>
<section id="why-this-matters-now"><h2>Why this matters now</h2>
<p>About 1 in 10 people have dyslexia. <a href="https://dyslexia.ie/info-hub/about-dyslexia/what-is-dyslexia/">Dyslexia Ireland</a>.</p>
<p>AHEAD&#x27;s 2023/24 report recorded 22,519 students registered with disability support services in Irish higher education, 8% of students. The largest category was specific learning difficulty, which includes dyslexia: 38.8%, or 8,738 students. <a href="https://www.ahead.ie/userfiles/files/shop/free/AHEAD%20Participation%20Rates%2023-24_digital.pdf">AHEAD, 2023/24 report</a>.</p>
<p>Many of these students rely on Grammarly. It now includes generative AI tools such as a paraphraser, citation finder and AI grader. <a href="https://wonkhe.com/wonk-corner/some-reasonable-adjustments-may-have-just-become-academic-misconduct/">Wonkhe, October 2025</a>.</p>
<p>Some universities now treat Grammarly as generative AI. Since August 2024, Notre Dame&#x27;s honour code has included editing tools like Grammarly when a lecturer bans generative AI. A University of North Georgia student was put on academic probation in 2024 after using Grammarly on an essay. <a href="https://www.insidehighered.com/news/tech-innovation/artificial-intelligence/2024/11/26/grammarly-ai-notre-dame-says-yes">Inside Higher Ed, November 2024</a>. <a href="https://www.fox5atlanta.com/news/grammarly-georgia-college-student-academic-probation-plagiarism-allegations">FOX 5 Atlanta</a>.</p>
<p>This creates a risk for disabled students: a support plan permitting Grammarly may date from its spell-checking role. A student with dyslexia could follow that plan while breaking the AI rules. <a href="https://wonkhe.com/wonk-corner/some-reasonable-adjustments-may-have-just-become-academic-misconduct/">Wonkhe, October 2025</a>.</p>
<p>Scribevo corrects the sentence the writer has already written. It handles dyslexic spellings such as fone, becos and freind, plus apostrophes and common grammar slips. It does not write, paraphrase, add ideas or change the writer&#x27;s style. Nothing changes until the writer accepts the correction. The words stay theirs.</p>
<p>From version 2.1.0, Scribevo uses no AI unless the writer turns it on. By default each sentence is checked against Scribevo's own spelling rules. An optional setting, “Also use AI for harder sentences”, adds an AI model limited to sentence correction. It stays off until the writer switches it on.</p>
<p>The aim is a tool a disability service could name in a student&#x27;s support plan because it corrects rather than generates writing. No university has approved Scribevo yet.</p>
<p>Project check, 4 October 2026: live on the Chrome Web Store at version 2.1.0; 248 backend and 69 extension tests pass.</p>
</section>
<h2>What Scribevo does</h2><p>Scribevo checks a sentence in context and presents a suggestion. The writer can accept it or dismiss it. The interface avoids a page full of red underlines and gives the person control over the edit.</p>
<pre>Illustrative example
You type:          i realy wnt to fon my freind
Scribevo suggests: I really want to phone my friend.</pre>
<p>It supports phonetic spellings, missing or swapped letters, apostrophes and some grammar errors. A dictionary can be searched using the spelling a person knows. Site-level controls let the writer pause assistance.</p>
<img class="diagram" src="../assets/scribevo-flow.svg" alt="Four steps: write a sentence, ask for support, review the suggestion, then accept or dismiss it.">
<h2>My work</h2><p>I developed the WordFlow research prototype, prepared a 6,571-pair training dataset and worked with a T5-based model using PyTorch and Hugging Face Transformers. I connected the research to a JavaScript browser extension and a Python FastAPI service. Four participant sessions informed the prototype's evaluation and interface work.</p><p>The project later developed into Scribevo. The current product uses spelling rules, with an optional AI-assisted correction stage that is off by default. The historical T5 prototype and the current product are different versions; results from one should not be presented as results for the other.</p>
<h2>Evidence, with the limits attached</h2><table><thead><tr><th scope="col">Evidence</th><th scope="col">What it tells us</th></tr></thead><tbody><tr><td>Published product</td><td>Project check, 4 October 2026: Scribevo version 2.1.0 is live on the Chrome Web Store.</td></tr><tr><td>Reported automated checks, 4 October 2026</td><td>The project check reports 248 backend and 69 extension tests pass. This is evidence about those tests, not proof that every website works.</td></tr><tr><td>Rules-only evaluation</td><td>70 out of 70 already-correct sentences were preserved. Harmful edits occurred in 3% of a separate 200-example held-out set. The provider-assisted stage was not part of this run.</td></tr><tr><td>Research prototype</td><td>6,571 training pairs and four participant sessions belong to the original academic work. The original model training and participant work were not rerun in the fresh release check.</td></tr></tbody></table>
<h2>Why this is useful for students</h2><p>The intended benefit is reducing the spelling work needed to express an idea, without taking over the student's writing. Reviewing a suggestion may also help a writer notice the intended spelling. Improved grades, confidence or learning outcomes have not been established by the current evaluation.</p>
<h2>Privacy is part of the design</h2><p>Only the sentence being checked is sent to the Scribevo service. By default it goes no further. If the writer turns on the AI setting, the sentence is also processed by Groq in the United States. No account is required. Cloud processing is a real trade-off: users should read the <a href="../scribevo/privacy.html">product privacy policy</a> before checking sensitive writing.</p>
<h2>What still needs work</h2><p>Context-dependent tense remains difficult. Browser editors vary, and automated checks do not replace testing in each real editor. There is no universal accuracy guarantee. Broader participant evaluation and more editor testing are needed.</p>
<h2>Engineering choices</h2><p>Separate the writing interface from the correction service. Measure harmful edits as well as successful corrections. Keep the suggested change reviewable. These decisions matter because a fluent replacement can still be the wrong replacement.</p><p>AI coding assistance was used during later engineering and verification work. The research origin, product decisions and evaluation limits are documented separately.</p>
<div class="note"><p>This is a public case study. Product source, datasets, trained artefacts, endpoints, credentials and implementation history remain private. Public descriptions cannot prevent someone from independently building a similar idea.</p></div>''')

page('case-studies/assistant-s.html','Assistant S','A public overview of a private Electron desktop assistant project.', '''
<p class="intro">A desktop assistant with an animated companion and a workspace for chat, study and everyday tasks.</p><div class="actions"><a class="button" href="https://github.com/Slooma951/Assistant-S-Showcase" target="_blank" rel="noopener noreferrer">Public project overview</a></div><img class="diagram" src="../assets/companion.svg" alt="Original conceptual illustration of a desktop companion, not a screenshot of the private application.">
<section id="project-evidence" class="project-evidence">
<p class="eyebrow">Inspect the engineering</p><h2>Project evidence</h2>
<p>JavaScript state handling, with selected source code, a runnable example and tests.</p>
<div class="evidence-grid">
<a href="https://github.com/Slooma951/Assistant-S-Showcase/tree/main/examples" target="_blank" rel="noopener noreferrer"><span class="evidence-label">Output</span><strong>Run the example ↗</strong><span>Inspect the selected code and compare its result with the saved JSON output.</span></a>
<a href="https://github.com/Slooma951/Assistant-S-Showcase/tree/main/evidence#methodology" target="_blank" rel="noopener noreferrer"><span class="evidence-label">Methodology</span><strong>Read the decisions ↗</strong><span>Source provenance, adaptations and the reasoning behind the example.</span></a>
<a href="https://github.com/Slooma951/Assistant-S-Showcase/tree/main/evidence#testing-results" target="_blank" rel="noopener noreferrer"><span class="evidence-label">Testing results</span><strong>8 example tests pass ↗</strong><span>Checked 4 October 2026. Test cases, rerun commands and verification record.</span></a>
</div><p>The selected function derives working, offline, waiting and error states from supplied task data. The recorded output uses mock tasks, providers and dialogue.</p><p class="evidence-limit">No personal account connections or conversations are included. These checks cover the selected function, not the full desktop application.</p></section>
<h2>What I wanted to build</h2><p>A personal desktop workspace that feels more approachable than a collection of disconnected tools. Assistant S combines a character-driven interface with practical screens for different kinds of work.</p>
<h2>What I built</h2><p>An Electron application with JavaScript modules, a local service and an animated 2D companion. The interface includes chat, study, tasks and settings. The character gives the app continuity while the task screens provide the useful part.</p><img class="diagram" src="../assets/assistant-flow.svg" alt="Choose a task, work with the assistant and review the result.">
<h2>Engineering focus</h2><p>Desktop packaging, a modular interface, clear connection states and deliberate user review for consequential actions. Combining these pieces has also meant working through device setup and differences between development and a packaged application.</p>
<h2>Current status</h2><p>A private personal software project, with a Windows packaged build checked in October 2026. It is not presented as a publicly available service. Account connections and device-specific setup vary.</p>
<h2>What this demonstrates</h2><p>Building and packaging a desktop application, connecting multiple interface areas, designing a consistent visual character and documenting the boundary between a working feature and a setup requirement. AI coding assistance was used during development.</p>
<div class="note"><p>This overview deliberately omits private conversations, account details, personal documents, internal paths, service configuration. Only the selected source example described above is public. The room screenshot contains no private application data. The public example uses synthetic inputs.</p></div>''')

page('case-studies/dvs-note.html','DVS Note','A TU Dublin team project combining notes, tasks, journaling and mood tracking.', '''
<p class="intro">An academic productivity and reflection project built at TU Dublin by Salem Elatrash, Daniel Aigbe and Adefolajuwon Adeniran.</p><h2>The idea</h2><p>Keep everyday planning and personal reflection in one application. Notes and tasks support organisation, while journals and mood views provide space to look back on the day.</p><img class="diagram" src="../assets/dvs-flow.svg" alt="Capture notes, tasks and journals; organise them in separate views; reflect using mood information.">
<h2>What the team built</h2><p>The archived repository contains dashboard, to-do, journal and login pages, plus API routes for account access, task operations, journal entries and mood statistics. The repository also contains mobile-related project work.</p><h2>Technology</h2><p>React and Next.js for the web application, Material UI for interface components and MongoDB connections in the account routes. Expo and Capacitor appear in the project's mobile tooling. These are repository observations, not a claim that every target has been rebuilt successfully today.</p><h2>My contribution</h2><p>I was one of the three student developers. This overview credits the application to the team. A precise feature-by-feature attribution has not been verified, so it does not assign the whole application or specific teammates' work to me.</p><h2>Status and lessons</h2><p>The repository is an archived academic record. It demonstrates team development across multiple application areas, and the need to document the actual project structure. It is not a current hosted product or a clinical wellbeing tool.</p><a class="button" href="https://github.com/Slooma951/Major-Group-Project">View the academic archive ↗</a>''')

page('privacy.html','Portfolio privacy','How this static portfolio handles visitors.', '''<p>Updated 3 October 2026.</p><p>This portfolio is a static site hosted through GitHub Pages. The portfolio's own pages have no contact form, account system or analytics script.</p><h2>Theme preference</h2><p>If you change the colour theme, the site saves that preference in your browser's local storage. You can clear it through your browser's site-data settings.</p><h2>Hosting and external links</h2><p>GitHub processes requests to serve the site under its own privacy practices. Links to LinkedIn, GitHub and the Chrome Web Store take you to services with their own policies.</p><h2>Product policies</h2><p>Scribevo is a separate product. Read its <a href="scribevo/privacy.html">privacy policy</a> for sentence processing and provider information. The portfolio's privacy description is not a policy for the private desktop project.</p>''')
page('terms.html','Portfolio terms','Terms for this portfolio and its public project descriptions.', '''<p>Updated 3 October 2026.</p><p>This website presents Salem Elatrash's professional work. Examples and conceptual diagrams explain project behaviour; they are not promises of accuracy or availability.</p><h2>Project material</h2><p>Public case studies do not grant access to private source code or confidential project material. Third-party software retains its own licence terms. The DVS Note academic archive has its own licence.</p><h2>Products and links</h2><p>The Scribevo Chrome listing and product policy describe the extension separately. Assistant S is a private personal project. External services may change without this portfolio being updated immediately.</p>''')

(ROOT/'sitemap.xml').write_text('<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'+''.join('<url><loc>https://slooma951.github.io/portfolio/'+x+'</loc></url>' for x in ['', 'case-studies/scribevo.html','case-studies/assistant-s.html','case-studies/dvs-note.html','privacy.html','terms.html','scribevo/','scribevo/privacy.html'])+'</urlset>',encoding='utf-8')
(ROOT/'robots.txt').write_text('User-agent: *\nAllow: /\nSitemap: https://slooma951.github.io/portfolio/sitemap.xml\n',encoding='utf-8')
